### ISSUE TITLE
Service page does not work in Chrome

### ISSUE THREAD

**Issue by georgezhao2010** [home-assistant/frontend#12898]
### The problem

Service page does not work in Chrome(version 102.0.5005.63 64bit), it reported "Error while loading page service.", I cleared all my browser's caches, but it still does not work. In Edge or Safari, It works normally.

Thanks.

### What version of Home Assistant Core has the issue?

core-2022.6.x

### What was the last working version of Home Assistant Core?

core-2021.9.x

### What type of installation are you running?

Home Assistant Core

### Anything in the logs that might be useful for us?

In browser's console,
```
hass-loading-screen.ts:11 Error loading page service SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at n.addFromStorage (27e09098.js:1:715)
    at 27e09098.js:1:1302
    at Object.decorateElement (ha-textfield.ts:7:1)
    at Object.<anonymous> (ha-textfield.ts:7:1)
    at Array.forEach (<anonymous>)
    at Object.decorateClass (ha-textfield.ts:7:1)
    at ha-textfield.ts:7:1
    at ha-textfield.ts:7:1
    at u.a (styles.ts:369:1)
```
