### ISSUE TITLE
Duration field in days is showing in hours

### ISSUE THREAD

**Issue by jimmyd-be** [home-assistant/frontend#18151]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When there is a field with device class duration and native unit of measurement in days the UI is showing it in hours. This is not really readable for users. For example the UI shows 3288:00:00 and this represents 137 days.

### Describe the behavior you expected

I think it is better to just show the days here. So that 137 days are shown instead of 3288:00:00.

### Steps to reproduce the issue

1. Show a duration day field in the UI
2. This will show the hours instead of days
3.
...

### What version of Home Assistant Core has the issue?

2023.10.1

**Comment by moorgrove** [comment]
+1 on this. The Entity Card and History graph Card shows the "raw" value but the rest of the card do convert the value to HH:MM:SS without ability to change unit of measurement in the entity settings.

<img width="1003" alt="Skärmavbild 2023-12-08 kl  10 37 16" src="https://github.com/home-assistant/frontend/assets/25015949/f2613bda-f298-47a7-ae79-e8d671aadc12">

<img width="591" alt="Skärmavbild 2023-12-08 kl  10 37 37" src="https://github.com/home-assistant/frontend/assets/25015949/17f198cf-daa8-4f8f-99df-384d303ac708">

**Comment by OscarHaraldsson** [comment]
+1 on this. I have a 14 days intervall entity that is showing days in the format HH:MM:SS.
![image](https://github.com/home-assistant/frontend/assets/48913385/a0a847ed-68fe-4b7e-809e-07de4308a74a)

Core 2023.12.1
Supervisor 2023.11.6
Operating System 11.2
Frontend 20231208.2

**Comment by igorsantos07** [comment]
At worst, this should be also configurable by the underutilized `format` property. So we can decide if we want to show a specific duration in a different scale, instead of having the `entities` card forcing that into hours.

As a workaround, I'm using `type: custom:template-entity-row`, as it gets the raw days value.

Also, this is almost duplicated by #18561 - it seems the issue is the same, but reporting a different unit and other cards.

**Comment by karwosts** [comment]
I don't have a perfect solution for this, but I did merge a change such that if you set a `display_precision` for a duration sensor, we will not attempt hh:mm:ss formatting, it will only display the exact original state formatted to the requested precision. 

Might not be a perfect solution but I hope that's a satisfying compromise.

**Comment by jimmyd-be** [comment]
Not fixed at all.

**Comment by freakyjoe8** [comment]
Yes, I can confirm that:

![image](https://github.com/home-assistant/frontend/assets/25949962/ba17f26d-afc6-4131-a9c0-2f4f268c2258)

vs

![image](https://github.com/home-assistant/frontend/assets/25949962/c9a1a7da-65fa-4d0c-94e2-0fdd31caeadb)

**Comment by karwosts** [comment]
I don't disagree with you, I know it's not perfect, though it's just the simplest compromise I could come up with. 

Another member added a while back this `hh:mm:ss` display format for all duration sensor, and I don't necessarily want to just go in and rip out their work, as this is somewhat subjective, and some people may prefer that format for some cases. E.g. if you had a sensor with a unit of seconds and the value was 10,000 seconds, many people would probably prefer the human readable format, versus saying that it must always display exactly in seconds. 

How to decide when to display one format versus another is not something I have a definitive answer for.

**Comment by igorsantos07** [comment]
Sorry, I never meant to spit on your work - I totally get you, and given the way issues are overlooked around here, I'm actually surprised anyone could do something about the topic. Congratulations! haha
What I meant is: to whomever arrives here in the future, that PR solely does _not_ fix the whole issue, it's mostly a mild patch, in a weird manner (given it depends on a sensor setting mostly related to decimal places).

That all said, to expand on your questioning of what could be a definitive solution for the issue: do you see any impediment on adding further functionality on [`format`](https://www.home-assistant.io/dashboards/entities/#format)? E.g., besides date/time/datetime, also allowing us to feed it a specific unit such as minutes/seconds/days, etc.

**Comment by karwosts** [comment]
I'm not so sure about `format`, as I don't think it fully solves this issue, given that like the more-info will still use the default display. Maybe if someone contributed a change to use format it might be accepted though 🤷‍♂️ . I think there's still some inconsistencies overall around format, given that it seems some cards support it and some do not.

**Comment by igorsantos07** [comment]
_stale-proof comment_

**Comment by tobse91** [comment]
I got a custom sensor with unit of measurement in days (at the moment 47 days, according to the state shown via developer settings). 
But when used in a tile card its showing me the raw number 1128:00:00 when the tile card is set to display precision "default (47)". When I change the settings for that card to "47", it shows 47 days as in the developer settings, which is correct. 

But it shouldnt make a difference in the first place. Possible bug?

**Comment by karwosts** [comment]
> But it shouldnt make a difference in the first place. Possible bug?

See my comment above:

>  I did merge a change such that if you set a display_precision for a duration sensor, we will not attempt hh:mm:ss formatting, it will only display the exact original state formatted to the requested precision.

> Might not be a perfect solution but I hope that's a satisfying compromise.

**Comment by Ghoelian** [comment]
Maybe it would be better to change the format based on the actual value?
Say a sensor reports 0.012 seconds, show 12 ms. But if it's reporting more than 1 second but less than say an hour, format it to minutes, etc. This way you shouldn't get those ridiculously large numbers.

**Comment by WebSpider** [comment]
> display_precision

(Sidenote: I am one of the maintainers of a custom integration for integrating Skoda vehicles into HA, `homeassistant-myskoda`)

I've tried to make this work on 2024.11.2, based on the following sensor:

```python
class InspectionInterval(MySkodaSensor):
    """The number of days before next inspection."""

    entity_description = SensorEntityDescription(
        key="inspection",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UnitOfTime.DAYS,
        translation_key="inspection",
    )
```
The `native_value` of this sensor is expressed in whole days as an integer. As stated by others in this issue, unit conversion to hours is always done in current frontend for some reason. It is highly unpractical to have a value of 200+ days expressed in hours for most humans. 

What I've tried to solve this is:

1) Set `_attr_precision = PRECISION_WHOLE`, no dice. There is still a conversion from days to hours
2) Set `suggested_display_precision` in the `entity_description` to PRECISION_WHOLE, no dice. Still converting
3) Tried setting `display_precision` in the integration. Sensor would throw a traceback because of 
`TypeError: SensorEntityDescription.__init__() got an unexpected keyword argument 'display_precision'`
4) Whenever I set the precision in the UI manually, including standard and all available options in the dropdown, conversion still takes place from days to hours.
5) Tried `native_precision` as well in the same way as `display_precision`. Same result.
6) Using the source, I found `_sensor_option_display_precision`, set it to PRECISION_WHOLE as well. Still conversion happening.

It is unclear to me what you mean by: "I did merge a change such that if you set a display_precision for a duration sensor, we will not attempt hh:mm:ss formatting, it will only display the exact original state formatted to the requested precision."

How do I make my `native_value` in my sensor that is expressed in days show up as days in frontend?

**Comment by karwosts** [comment]
> It is unclear to me what you mean by: "I did merge a change such that if you set a display_precision for a duration sensor, we will not attempt hh:mm:ss formatting, it will only display the exact original state formatted to the requested precision."

We had to revert that change, so that doesn't exist anymore. 

> How do I make my native_value in my sensor that is expressed in days show up as days in frontend?

Don't make it a `duration` device_class. That's the only way.

**Comment by WebSpider** [comment]
> > How do I make my native_value in my sensor that is expressed in days show up as days in frontend?
> 
> Don't make it a `duration` device_class. That's the only way.

Does that mean this issue will not be fixed?

**Comment by karwosts** [comment]
> Does that mean this issue will not be fixed?

Hard to say, its open source. A fix could come from anyone at any time. I'm not sure what shape or form a fix would look like, or how you make a change that doesn't break someone else's usecase in a different sensor.

**Comment by bonroyage** [comment]
I ran into this inconvenience at the opposite end of the spectrum. The average round trip sensors of the ping integration are milliseconds, so they appear as `0.004`. The average processing speed of the AdGuard integration doesn't have the DURATION device_class so they appear as `10 ms` on the dashboard.

It's entirely possible that I'm lacking background knowledge on the duration device class and the reason why the values
appear as they currently do. Still, I'd like to make a suggestion for how they are displayed (see table below).

This could be achieved by modifying [millisecondsToDuration](https://github.com/home-assistant/frontend/blob/dev/src/common/datetime/milliseconds_to_duration.ts), because this is the method that is called from [duration.ts](https://github.com/home-assistant/frontend/blob/dev/src/common/datetime/duration.ts) (after coming from [computeStateDisplayFromEntityAttributes](https://github.com/home-assistant/frontend/blob/dev/src/common/entity/compute_state_display.ts#L72-L82)). Later I noticed there's also a [secondsToDuration](https://github.com/home-assistant/frontend/blob/dev/src/common/datetime/seconds_to_duration.ts) function that might also have to be changed then for consistency.

Then I stumbled upon the [formatDuration](https://github.com/home-assistant/frontend/blob/dev/src/common/datetime/format_duration.ts) function, which returns longer outputs (for completeness, also added to the table). Would there be a reason why this function can't be used to format the state? Perhaps the `unitDisplay` can be configured to allow `short` or `narrow`?

|     | Input (ms) | Current   | Proposed      | `formatDuration` |
|-----|------------|-----------|---------------|------------------|
|     | 0          | null      | null          | null             |
| 💡️ | 1          | 0.001     | 1 ms          | 1 millisecond    |
| 💡  | 10         | 0.010     | 10 ms         | 10 milliseconds  |
| 💡  | 100        | 0.100     | 100 ms        | 100 milliseconds |
| 💡  | 1000       | 1         | 1 s           | 1 second         |
| 💡  | 1001       | 1.001     | 1.001 s       | 1 second         |
|     | 65000      | 1:05      | 1:05          | 1:05             |
|     | 3665000    | 1:01:05   | 1:01:05       | 1:01:05          |
|     | 39665050   | 11:01:05  | 11:01:05      | 11:01:05         |
| 💡  | 86400000   | 24:00:00  | 1 d           | 1 day 0:00:00    |
| 💡  | 932093000  | 258:54:53 | 10 d 18:54:53 | 10 days 18:54:53 |

To make it a little more interesting: there are also reversed methods, like [createDurationData](https://github.com/home-assistant/frontend/blob/dev/src/common/datetime/create_duration_data.ts) and [durationToSeconds](https://github.com/home-assistant/frontend/blob/dev/src/common/datetime/duration_to_seconds.ts). Would it break anything in these parsers if the formatters are changed?

**Comment by karwosts** [comment]
Some of those look like nice suggestions :+1:
