### ISSUE TITLE
No entities listed (device page, dropdowns...)

### ISSUE THREAD

**Issue by ghisch** [home-assistant/frontend#25363]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After updating to version 2025.5.0, no entities are listed in the Entities page or in entity dropdowns, due to a JavaScript error caused by some entities lacking a name.

### Describe the behavior you expected

Entities are listed

### Steps to reproduce the issue

Have entities with no defined name
Open the entities page

### What version of Home Assistant Core has the issue?

2025.5.0

### What was the last working version of Home Assistant Core?

2025.4.4 (I think)

### In which browser are you experiencing the issue?

Chrome

### Javascript errors shown in your browser console/inspector

```txt
reactive-element.ts:1369 Uncaught (in promise) TypeError: e.toLowerCase is not a function
    at a (strip_prefix_from_entity_name.ts:13:43)
    at r (compute_entity_name.ts:55:12)
    at HTMLElement.<anonymous> (ha-config-entities.ts:677:28)
    at HTMLElement.a [as _filteredEntitiesAndDomains] (memoize-one.esm.js:37:35)
    at HTMLElement.render (ha-config-entities.ts:748:12)
    at HTMLElement.update (lit-element.ts:166:24)
    at HTMLElement.performUpdate (reactive-element.ts:1503:14)
```

### Additional information

This error appears to originate from this line:
https://github.com/home-assistant/frontend/blob/c7e79998a4380ce8942aa03d8085045e9d1343a2/src/common/entity/strip_prefix_from_entity_name.ts#L13

Root cause:

Entities without a defined name (but with has_entity_name: true) trigger the error when .toLowerCase() is called on undefined.

Example of problematic entity:
```
{
    "entity_id": "media_player.home_cinema_salon",
    "device_id": "4c88044b857e99504b93c6aa4985ce58",
    "labels": [],
    "platform": "cast",
    "has_entity_name": true
}
```

Script used to identify problematic entities:

```
Object.values(document.querySelector("home-assistant").hass.entities).forEach(function(e) {
    try {
        var a = e.name.toLowerCase();
    } catch (error) {
        console.log(JSON.stringify(e, null, 4));
    }
})
```

Findings:
- 42 entities are causing the issue due to missing name values.
- These entities render the entire entities UI unusable.

**Comment by shirou93** [comment]
Hi, i have issues with display some elements but only with proxy after update to 2025.5.0

**Comment by piitaya** [comment]
Hi 👋
We check for device name and name before using this function so `undefined` name are not an issue. 

```ts
  if (deviceName && name) {
    return stripPrefixFromEntityName(name, deviceName) || name;
  }
```

Can you provide the list of problematic entities by running this code ? I guess some of your entities are name as number instead of string.  (similar to this : https://github.com/home-assistant/frontend/issues/25163)

```
Object.values(document.querySelector("home-assistant").hass.entities).forEach(function(e) {
    try {
        var a = e.name?.toLowerCase();
    } catch (error) {
        console.log(JSON.stringify(e, null, 4));
    }
})
```

**Comment by ghisch** [comment]
Yes indeed, sorry for my wrong analysis. It's linked to https://github.com/home-assistant/frontend/issues/25163

```js
Object.values(document.querySelector("home-assistant").hass.entities).forEach(function(e) {
    try {
        var a = e.name?.toLowerCase();
    } catch (error) {
        console.log(JSON.stringify(e, null, 4));
    }
})

{
    "entity_id": "switch.107782925_107782925",
    "device_id": "99c0238cd4c84b6e850a2072b2811e5a",
    "labels": [],
    "translation_key": "parental_control",
    "platform": "bbox",
    "has_entity_name": true,
    "name": 107782925
}
```

**Comment by TomTomTom1975** [comment]
Hi I tried to find entities which could cause the problem by executing the following code while opening the entities page:

```
Object.values(document.querySelector("home-assistant").hass.entities).forEach(function(e) {
    try {
        var a = e.name?.toLowerCase();
    } catch (error) {
        console.log(JSON.stringify(e, null, 4));… 
```
I get the response `undefined`

**Comment by ghisch** [comment]
Try this in the devices page

```javascript
Object.values(document.querySelector("home-assistant").hass.devices).forEach(function(e) {
    try {
        var a = (e.name_by_user || e.name)?.trim();
    } catch (error) {
        console.log(JSON.stringify(e, null, 4))
    }
})
```

**Comment by ghisch** [comment]
And try this in the entities pages

```javascript
Object.values(document.querySelector("home-assistant").hass.entities).forEach(function(e) {
    try {
        var a = e.name?.toLowerCase();
    } catch (error) {
        console.log(JSON.stringify(e, null, 4));
    }
})
```

Be aware, the end of the code you pasted is wrong (your code ends with `;… `)

**Comment by ausfas** [comment]
I initially thought it was bubble card HACS but doesn't look like its an issue with Bubble card but issue with HA core issue. The same error was coming up in console everywhere when ever any entity or name is selected so I installed 2025.4.1 functionality restored but error still there. Installed 2025.5.x error came back and same issue with the functionality. Now installed 2025.6.0b3 functionality restored but error still there. So not sure which bug has partially resolved this issue. I hope will be fully fixed for 6.0 release
Similar to https://github.com/home-assistant/frontend/issues/25163

**Comment by ausfas** [comment]
> Hi I tried to find entities which could cause the problem by executing the following code while opening the entities page:
> 
> ```
> Object.values(document.querySelector("home-assistant").hass.entities).forEach(function(e) {
>     try {
>         var a = e.name?.toLowerCase();
>     } catch (error) {
>         console.log(JSON.stringify(e, null, 4));… 
> ```
> 
> I get the response `undefined`
> 
> I printed all entity names (e.name) to the console and sorted it ascending. There is no numeric entity name in.

Same here, got undefined for both versions of the code by @ghisch and by @piitaya 
I also used the code provided  by @piitaya for https://github.com/home-assistant/frontend/issues/25163 which provides a a list of lot devices have null names but many of them are no ZHA devices and UI works fine if they remain enabled. Its the ZHA integration or devices underneath (I guess).

**Comment by ausfas** [comment]
hi @piitaya, is there any thing else that I can do that may help you debug this issue as I would be two releases behind if this is not fixed.😞

@ghisch, is your issue resolved?

**Comment by ghisch** [comment]
Yes my issue is resolved. In my case, since the device with the integer name was created by a custom integration of my router, I just changed the name of the device to include a character directly on my router portal, and the change was replicated by the custom integration, fixing my issue in the front end.

**Comment by ausfas** [comment]
> Hi I tried to find entities which could cause the problem by executing the following code while opening the entities page:
> 
> ```
> Object.values(document.querySelector("home-assistant").hass.entities).forEach(function(e) {
>     try {
>         var a = e.name?.toLowerCase();
>     } catch (error) {
>         console.log(JSON.stringify(e, null, 4));… 
> ```
> 
> I get the response `undefined`
> 
> I printed all entity names (e.name) to the console and sorted it ascending. There is no numeric entity name in.

@TomTomTom1975, any update at your end ?

**Comment by ausfas** [comment]
Finally resolved it.
Using this code as hass is not defined initially. Hope this will help others.
```

(function () {
  // Safely get `hass` from Home Assistant frontend
  const hass = document.querySelector("home-assistant")?.hass;

  if (!hass) {
    console.error(" Could not find the Home Assistant 'hass' object. Are you in the right panel?");
    return;
  }

  const fatalEntities = [];

  Object.entries(hass.states).forEach(([id, state]) => {
    const friendlyName = state.attributes?.friendly_name;
    const nameByUser = state.attributes?.name_by_user;

    if (friendlyName !== undefined && typeof friendlyName !== "string") {
      console.error(" CRITICAL: .toLowerCase() will fail on friendly_name:", id, friendlyName);
      fatalEntities.push({
        entity_id: id,
        attribute: "friendly_name",
        current: friendlyName,
        suggested_fix: String(friendlyName),
      });
    }

    if (nameByUser !== undefined && typeof nameByUser !== "string") {
      console.error(" CRITICAL: .toLowerCase() will fail on name_by_user:", id, nameByUser);
      fatalEntities.push({
        entity_id: id,
        attribute: "name_by_user",
        current: nameByUser,
        suggested_fix: String(nameByUser),
      });
    }
  });

  if (fatalEntities.length === 0) {
    console.log(" No invalid attributes found.");
  } else {
    console.warn(` Found ${fatalEntities.length} invalid attributes that will break toLowerCase():`);
    console.table(fatalEntities);
  }

  return fatalEntities;
})();
```
The entry was SLZB ZHA coordinator that has `"original_name":2` which is a number not a string.
I removed this entry as it was SLZB06 as I'm now using SLZB06M  which uses EFR not Texas chip (CC265x) but others may run into this problem @piitaya , you may need to think of a solution. 

```
{"aliases":[],"area_id":null,"categories":{},"capabilities":{"state_class":"total"},"config_entry_id":"01J3Q9ABM1QZV3DE4ARRW5DN0T","config_subentry_id":null,"created_at":"2024-09-02T02:17:01.226502+00:00","device_class":null,"device_id":"2743563908b8b7acfd61780c69e678a3","disabled_by":null,"entity_category":"diagnostic","entity_id":"sensor.texas_instruments_cc2652_2","hidden_by":null,"icon":null,"id":"7cefda741e802bd1eafa212190bb8738","has_entity_name":true,"labels":[],"modified_at":"2025-06-02T01:22:02.798395+00:00","name":null,"options":{"cloud.alexa":{"should_expose":false},"conversation":{"should_expose":false},"cloud.google_assistant":{"should_expose":false}},"original_device_class":null,"original_icon":null,"original_name":2,"platform":"zha","supported_features":0,"translation_key":null,"unique_id":"00-12-4b-00-2c-da-38-ca_counters_Retry_NONE_2","previous_unique_id":null,"unit_of_measurement":null},
```

**Comment by Rudd-O** [comment]
I ran the fatalEntities code in my instance, and it told me I don't have any bad entities.  Array returned is zero length.
