### ISSUE TITLE
Cannot set new thermostat value

### ISSUE THREAD

**Issue by pszypowicz** [home-assistant/frontend#5710]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

After upgrade to 109.x I'm not able to change desired temperature on the thermostat card. I can modify the temperature from the details of the card. 

![Screenshot_2020-05-02 Home Assistant](https://user-images.githubusercontent.com/2733699/80861071-84c3c300-8c6c-11ea-9d7a-474c1c706d92.png)
![Screenshot_2020-05-02 Home Assistant(1)](https://user-images.githubusercontent.com/2733699/80861085-9d33dd80-8c6c-11ea-8f88-8a16bdc6d9ab.png)

I'm using zwave valve thermostats.

## Expected behavior

I should be able to change it from the frontend panel. 

## Environment

- Home Assistant release with the issue: 0.109.x
- Last working Home Assistant release (if known): 0.108.x
- Browser and browser version: firefox and chrome
- Operating system: ubuntu/android 

## State of relevant entities

![Screenshot_2020-05-02 Narzędzia deweloperskie - Home Assistant](https://user-images.githubusercontent.com/2733699/80861200-3ebb2f00-8c6d-11ea-8847-234bf009dca0.png)

```yaml
hvac_modes: []
min_temp: 7
max_temp: 35
current_temperature: 22.9
temperature: 21
node_id: 7
value_index: 1
value_instance: 1
value_id: '72057594160660498'
friendly_name: Kaloryfer w kuchni
supported_features: 1
```

## Javascript errors shown in your browser console/inspector

```txt
TypeError: this._setTemp.toFixed is not a function
hui-thermostat-card.ts:184:38
```

**Comment by bramkragten** [comment]
Why is the state unknown?

**Comment by pszypowicz** [comment]
No idea. I turned off all automation (appdaemon), restarted the home assistant and tried to heal z-wave network. Climate entity state is still unknown. 

Please let me know if additional information from my side are needed.
