### ISSUE TITLE
Dashboard tab configuration not possible in YAML

### ISSUE THREAD

**Issue by pedolsky** [home-assistant/frontend#14255]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I try to configure or edit a dashboard tab and select „edit in YAML mode“, I'm getting empty windows:

![DC348602-F053-4F35-9B50-591084D5B68F](https://user-images.githubusercontent.com/71203830/199349036-dd15cca4-eee8-44b8-935f-e5b4b7227fff.jpeg)

This makes the editing of subviews in particular quite inconvenient, because I can set/edit an individual backpath only in YAML mode (or in raw config, but this way I must scroll through 1000s of lines).

### Describe the behavior you expected

Tabbing the 3 dots top right, select YAML mode and get YAML mode :)

### Steps to reproduce the issue

1. Call „configure UI“
2. Select a dashboard tab by tapping the pencil symbol
3. Tap the 3 dots right top
4. Select „edit in YAML mode“
...

### What version of Home Assistant Core has the issue?

core-2022.12.0

### What was the last working version of Home Assistant Core?

core-2022.10.x

### In which browser are you experiencing the issue with?

Google Chrome 107.0.5304.66, Safari 16.1

### Which operating system are you using to run this browser?

iPadOS 16.1

**Comment by Tsvetkovv** [comment]
I have got the same. Here is a console error
```js
Uncaught (in promise) TypeError: t.setValue is not a function
    at F.value (hui-entity-editor.ts:19:1)
    at F._$AE (styles.ts:371:1)
    at F.performUpdate (styles.ts:371:1)
    at F.scheduleUpdate (styles.ts:371:1)
    at F._$EC (styles.ts:371:1)
```
I noticed it worked before I install [mini-graph-card](https://github.com/kalkih/mini-graph-card#entities-object) and made some adjustments for dashboard. I tried to remove its resource, the issue was not gone

**Comment by M-t-t-h** [comment]
same error (same console error too).
I just install HASS-core and more on a VM (on a Syno).

Will check if i can do somethink on my side and tell you.

**Comment by pedolsky** [comment]
Worked for a short time in 2022.12.0b3, but after updating to 0b4, it's gone again.

**Comment by hugokernel** [comment]
Hi, same problem here.

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

**Comment by ttimasdf** [comment]
Still having this issue on 20230503.3
